### ISSUE TITLE
undefined method `bag_item'

### ISSUE THREAD

**Issue by jonljh** [johnbellone/vault-cluster-cookbook#12]
Hi.  I'm testing this cookbook on ubuntu instances, but i get the following error during bootstrap:

> undefined method `bag_item' for VaultCookbook::Resource::VaultConfig

Any thoughts on what the issue is?

jon

**Comment by jonljh** [comment]
Someone pointed out to me that the problem here is that the newer, hashicorp-vault cookbook no longer uses bag_item; also metadata.rb file pointed to 2.1 which could be an issue.  Went ahead and adjusted to hashicorp-vault 2.1.0 as dependency.  This will work as a temporary fix, but it would be nice to have the cookbook compatible with the latest hashicorp-vault cookbook.

**Comment by johnbellone** [comment]
I'll try to take a look at this over the next few days.
